tests/src/main/java/org/hibernate/beanvalidation/tck/tests/messageinterpolation/MessageInterpolationTest.java

MessageInterpolationTest.testRecursiveMessageInterpolation()
* https://hibernate.atlassian.net/projects/BVTCK/issues/BVTCK-73

BVTCK-73 Expected and actual value switched in

---

pom.xml

* https://hibernate.atlassian.net/browse/BVTCK-85

BVTCK-85 Set the version of the maven-deploy-plugin

---

settings-example.xml

- https://hibernate.atlassian.net/browse/BVTCK-86

BVTCK-86 Clean up the settings-example.xml file

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/constraintdefinition/ConstraintDefinitionsTest.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/constraintdefinition/Movie.java
tests/src/main/resources/tck-audit.xml

- https://hibernate.atlassian.net/browse/BVTCK-87

BVTCK-87 Add tests for @Repeatable annotations

---

pom.xml

* https://hibernate.atlassian.net/browse/BVTCK-91

BVTCK-91 Base the TCK on BV 2.0.0.Alpha1

---

changelog.txt
documentation/src/main/docbook/en-US/installation.xml
setup-examples/readme.md

* https://hibernate.atlassian.net/browse/BVTCK-94

BVTCK-94 Update links to BV and our issue tracker

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/builtinconstraints/BuiltinValidatorOverrideTest.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/messageinterpolation/MessageInterpolationTest.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/time/ClockProviderFutureTest.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/time/ClockProviderPastTest.java

* https://hibernate.atlassian.net/browse/BVTCK-95
* https://hibernate.atlassian.net/browse/BVTCK-96

Assorted minor fixes to the TCK

---

documentation/src/main/asciidoc/sigtest.asciidoc

- https://hibernate.atlassian.net/browse/BVTCK-62
Updated documentation related to running signature test. Only Maven related part is left. Also replaced tabs in xml formatting to spaces (tabs were putting too much blank space :) )

BVTCK-62 Investigate how signature files could be created as part of the build 

---

documentation/pom.xml
pom.xml

* https://hibernate.atlassian.net/browse/BVTCK-111

BVTCK-111 Dynamically generate the current copyright year

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/integration/cdi/managedobjects/ManagedObjectsTest.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/integration/cdi/managedobjects/MapKeyValueExtractorUsingDependencyInjection.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/integration/cdi/managedobjects/MapValueValueExtractorUsingDependencyInjection.java
tests/src/main/resources/org/hibernate/beanvalidation/tck/tests/integration/cdi/managedobjects/validation-ManagedObjectsTest.xml

* https://hibernate.atlassian.net/browse/BVTCK-125

BVTCK-125 Test that ValueExtractors defined in XML are CDI enabled

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/validatorresolution/CustomConstraint.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/validatorresolution/SubClassC.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/validatorresolution/SubClassD.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/validatorresolution/ValidatorResolutionTest.java

* https://hibernate.atlassian.net/browse/BVTCK-123

BVTCK-123 Add tests for non getter method and constructor for 5.7.4 - d

---

pom.xml
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/constraintcomposition/ConstraintCompositionTest.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/constraintcomposition/FrenchZipcodeWithDefaultOverridesAttributeName.java

* https://hibernate.atlassian.net/browse/BVTCK-155
Should be merged after: https://github.com/hibernate/hibernate-validator/pull/756

BVTCK-155 Add a test for @OverridesAttribute default name()

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/containerelement/ContainerElementConstraintGroupValidationTest.java

* https://hibernate.atlassian.net/browse/BVTCK-138

BVTCK-138 Add tests for group conversions on container elements

---

documentation/pom.xml
documentation/src/main/asciidoc/appeals-process.asciidoc
documentation/src/main/asciidoc/configuration.asciidoc
documentation/src/main/asciidoc/installation.asciidoc
documentation/src/main/asciidoc/introduction.asciidoc
documentation/src/main/asciidoc/reporting.asciidoc
setup-examples/ant/build.properties
setup-examples/ant/readme.md
setup-examples/maven/pom.xml
setup-examples/maven/readme.md
setup-examples/readme.md

* https://hibernate.atlassian.net/browse/BVTCK-134
* https://hibernate.atlassian.net/browse/BVTCK-79
+ various other infelicities noted while reading the doc and readmes.

BVTCK-134 BVTCK-79 TCK documentation and setup updates

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/builtinconstraints/NegativePositiveConstraintsTest.java

* https://hibernate.atlassian.net/browse/BVTCK-161

BVTCK-161 Add tests for @PositiveOrZero and @NegativeOrZero

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/valueextraction/builtin/OptionalValueExtractorTest.java

* https://hibernate.atlassian.net/browse/BVTCK-122

BVTCK-122 Improve Optional and al. tests

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/metadata/ParameterDescriptorTest.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/metadata/PropertyDescriptorTest.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/metadata/ReturnValueDescriptorTest.java

* https://hibernate.atlassian.net/browse/BVTCK-163

BVTCK-163 Add tests for ContainerElementDescriptor#getElementClass()

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/builtinconstraints/EmailConstraintTest.java

* https://hibernate.atlassian.net/browse/BVTCK-131

BVTCK-131 Adjust @Email constraint tests

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/validation/graphnavigation/containerelement/NestedCascadingOnContainerElementsTest.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/validation/graphnavigation/containerelement/model/Address.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/validation/graphnavigation/containerelement/model/AddressType.java

* https://hibernate.atlassian.net/browse/BVTCK-158

BVTCK-158 Add a test for cascading validation with 2 inner extractions

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/metadata/ContainerElementTypeDescriptorTest.java

* https://hibernate.atlassian.net/browse/BVTCK-169

BVTCK-169 Add some tests regarding container element metadata

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/validation/graphnavigation/containerelement/LegacyValidOnContainerCascadingTest.java

* https://hibernate.atlassian.net/browse/BVTCK-166

BVTCK-166 Add a test for the legacy behavior of @Valid on arrays

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/validatorresolution/CustomConstraint.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/validatorresolution/SubClassE.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/validatorresolution/SubClassF.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/validatorresolution/SubClassG.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/validatorresolution/SubClassH.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/validatorresolution/SubClassI.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/validatorresolution/ValidatorResolutionTest.java

* https://hibernate.atlassian.net/browse/BVTCK-143

BVTCK-143 Add tests for "ConstraintValidator resolution algorithm"

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/containerelement/NestedContainerElementConstraintsTest.java

* https://hibernate.atlassian.net/browse/BVTCK-170

BVTCK-170 Add tests for nested container element traversing

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/valueextraction/unwrapping/ValueExtractionUnwrappingTest.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/valueextraction/unwrapping/model/UnwrapByDefaultIntegerWrapperValueExtractor.java

* https://hibernate.atlassian.net/browse/BVTCK-165
* https://hibernate.atlassian.net/browse/BVTCK-168

BVTCK-165 - BVTCK-168 Additional tests for implicit unwrapping

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/inheritance/method/invaliddeclarations/InvalidMethodConstraintDeclarationTest.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/inheritance/method/invaliddeclarations/service/AbstractCalendarService.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/inheritance/method/invaliddeclarations/service/AnotherCalendarService.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/inheritance/method/invaliddeclarations/service/CalendarService.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/inheritance/method/invaliddeclarations/service/YetAnotherCalendarService.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/inheritance/method/invaliddeclarations/service/impl/ImplementationAddingParameterConstraints.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/inheritance/method/invaliddeclarations/service/impl/ImplementationMarkingParameterAsCascaded.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/inheritance/method/invaliddeclarations/service/impl/ImplementationOfCascadingAndNonCascadingInterfaces.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/inheritance/method/invaliddeclarations/service/impl/ImplementationOfCascadingInterfaceExtendingUncascadingSuperClass.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/inheritance/method/invaliddeclarations/service/impl/ImplementationOfConstrainedAndUnconstrainedInterfaces.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/inheritance/method/invaliddeclarations/service/impl/ImplementationOfConstrainedInterfaceExtendingUnconstrainedSuperClass.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/inheritance/method/invaliddeclarations/service/impl/SubClassAddingParameterConstraints.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/inheritance/method/invaliddeclarations/service/impl/SubClassMarkingParameterAsCascaded.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/validation/graphnavigation/containerelement/CascadingOnContainerElementsTest.java

* https://hibernate.atlassian.net/browse/BVTCK-159

BVTCK-159 Add specific tests for container element cascading on method parameters and al.

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/valueextraction/unwrapping/ValueExtractionUnwrappingTest.java

* https://hibernate.atlassian.net/browse/BVTCK-173

BVTCK-173 Take into account value unwrapping API changes

---

documentation/src/main/asciidoc/reporting.asciidoc
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/AbstractTCKTest.java
tests/src/main/java/org/hibernate/beanvalidation/tck/util/shrinkwrap/ArchiveBuilder.java

https://hibernate.atlassian.net/projects/BVTCK/issues/BVTCK-177

BVTCK-177 Improving the way how the AssertJ JAR is added to test WARs

---

standalone-container-adapter/src/main/java/org/hibernate/validator/tck/arquillian/ArchiveClassLoader.java

* https://hibernate.atlassian.net/browse/BVTCK-74

BVTCK-74 Make ArchiveClassLoader work with JDK 9

---

tests/src/main/java/org/hibernate/beanvalidation/tck/util/shrinkwrap/ArchiveBuilder.java
tests/src/main/java/org/hibernate/beanvalidation/tck/util/shrinkwrap/URLPackageScanner.java

* https://hibernate.atlassian.net/browse/BVTCK-192
IMPORTANT: this PR is against the 2.0 branch.

 BVTCK-192 Do not use an internal ShrinkWrap API in ArchiveBuilder

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/validation/graphnavigation/containerelement/LegacyValidOnContainerCascadingTest.java

* https://hibernate.atlassian.net/browse/BVTCK-195

BVTCK-195 Remove test from the TCK which relates to undefined spec behavior

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/constraintcomposition/FrenchAddressListContainer.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/constraintcomposition/FrenchAddressMixDirectAnnotationAndListContainer.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/constraintcomposition/FrenchZipcodeListContainerConstraintValidator.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/constraintcomposition/FrenchZipcodeMixDirectAnnotationAndListContainerConstraintValidator.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/constraints/customconstraint/ZeroConstraintValidator.java

* https://hibernate.atlassian.net/browse/BVTCK-197

BVTCK-197 Fix mismatch between registered constraints and defined constraints

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/bootstrap/BootstrapConfigurationWithValidatedExecutableTypesContainingNONETest.java

* https://hibernate.atlassian.net/browse/BVTCK-198

BVTCK-198 Fix incorrect test BootstrapConfigurationWithValidatedExecutableTypesContainingNONETest

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/metadata/CustomComposingConstraint.java

* https://hibernate.atlassian.net/browse/BVTCK-199

BVTCK-199 Do not use the @Size constraint on an int

---

tests/src/main/resources/org/hibernate/beanvalidation/tck/tests/xmlconfiguration/constraintdeclaration/propertylevel/user-constraints-InvalidGroupConversionInPropertyLevelOverridingTest.xml

https://hibernate.atlassian.net/browse/BVTCK-205
@mbenson I suppose this is what you had in mind?

BVTCK-205 Improve consistency of InvalidGroupConversionInPropertyLevelOverridingTest

---

documentation/src/main/asciidoc/appeals-process.asciidoc

Signed-off-by: Gunnar Morling <gmorling@redhat.com>
@starksm64, this updates the appeals process docs as per your template from CDI. It'll need another release build and updated SHA values in the PRs.
/CC gsmet.

Updating appeals process

---

README.md
distribution/pom.xml
distribution/src/main/assembly/dist.xml
documentation/pom.xml
documentation/src/main/asciidoc/appeals-process.asciidoc
documentation/src/main/asciidoc/preface.asciidoc
documentation/src/main/asciidoc/sigtest.asciidoc
pom.xml
setup-examples/artifact-install.sh
setup-examples/maven/pom.xml
setup-examples/readme.md
standalone-container-adapter/pom.xml
tests/pom.xml

Signed-off-by: Scott M Stark <starksm64@gmail.com>
This includes additional changes needed to be able to build and release the TCK in the CI environment.

Update TCK for Jakarta EE 9 package name change and CI env changes

---

tests/src/main/java/org/hibernate/beanvalidation/tck/tests/integration/ee/cdi/ConstraintValidatorInjectionTest.java

A mistake was introduced in the test during the work on BV 3.0.
The 2.0 branch was OK. I reported what we had in the 2.0 branch in master.

Fix integration.ee.cdi.ConstraintValidatorInjectionTest

---

README.md
checkstyle.xml
distribution/pom.xml
distribution/src/main/assembly/dist.xml
documentation/pom.xml
documentation/src/main/asciidoc/installation.asciidoc
documentation/src/main/asciidoc/sigtest.asciidoc
pom.xml
setup-examples/artifact-install.sh
setup-examples/maven/pom-local.xml
setup-examples/maven/pom.xml
setup-examples/maven/readme.md
setup-examples/maven/src/test/resources/arquillian.xml
setup-examples/readme.md
standalone-container-adapter/pom.xml
standalone-container-adapter/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
tests/pom.xml
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/methodvalidation/ExecutableValidationIgnoresValidatedExecutableXmlSettingsTest.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/methodvalidation/ValidateConstructorParametersTest.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/methodvalidation/constraint/ValidStockItemRecord.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/methodvalidation/model/ComplexStockItemRecord.java
tests/src/main/java/org/hibernate/beanvalidation/tck/tests/methodvalidation/model/StockItemRecord.java
tests/src/main/java/org/hibernate/beanvalidation/tck/util/JavaFXTestsMethodSelector.java
tests/src/main/resources/org/hibernate/beanvalidation/tck/tests/bootstrap/customprovider/jakarta.validation.spi.ValidationProvider
tests/src/main/resources/org/hibernate/beanvalidation/tck/tests/integration/cdi/managedobjects/jakarta.validation.valueextraction.ValueExtractor
tests/src/main/resources/org/hibernate/beanvalidation/tck/tests/integration/cdi/managedobjects/jakarta.validation.valueextraction.ValueExtractor-throwsException
tests/src/main/resources/org/hibernate/beanvalidation/tck/tests/valueextraction/declaration/jakarta.validation.valueextraction.ValueExtractor
tests/src/main/resources/tck-tests.xml

This has been tested against the glassfish-web-7.0.9 version and passes all tests

Updates for 3.1.0-M2 milestone
